### ISSUE TITLE
Address-->transaction-->fees error

### ISSUE THREAD

**Issue by KenianShi** [FUSIONFoundation/BlockExplorer#3]
i found there is an error when i use the BlockExplorer.i click any of the address show in the Explorer,then i found the transaction fees is .00000002.that is not the correct tx fee
<img width="889" alt="微信图片_20190905161652" src="https://user-images.githubusercontent.com/28284045/64324282-a5158200-cff8-11e9-8929-e74514d8527b.png">

**Comment by JoeyKhd** [comment]
Hi @shiknian 

Thank you for raising this issue. The issue has been resolved in the following commit: https://github.com/FUSIONFoundation/BlockExplorer/commit/31bfa5df254b73dac5f9ddb9916810efa492f0e2
